# Generated by Django 4.1.3 on 2023-08-12 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='webo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('time', models.CharField(max_length=32, verbose_name='时间')),
                ('data', models.CharField(max_length=128, verbose_name='内容')),
                ('url', models.CharField(max_length=128, verbose_name='链接')),
            ],
        ),
    ]
