# Generated by Django 4.1.3 on 2023-08-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_webo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webo',
            name='data',
            field=models.CharField(max_length=1024, verbose_name='内容'),
        ),
    ]
