# Generated by Django 4.1.3 on 2023-08-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_webo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='名称'),
        ),
    ]
